### ISSUE TITLE
[Ask for test dataset]

### ISSUE THREAD

**Issue by jkonyourmark** [TencentAI4S/tfold#1]
I have been greatly impressed by your work in the field and am currently developing a model to predict antibody-antigen complexes. I believe comparing our models using the same test dataset, specifically the SAbDab-22H2-AbAg and SAbDab-22H2-NanoAg datasets used in your tFold-ag model, would be highly beneficial.

Could you kindly share these datasets or guide me on how to access them? Your support would be invaluable to our research efforts.

Thank you for considering my request. I look forward to any responses from you.

**Comment by doublechenching** [comment]
The test dataset has been introduced in the readme Dataset section. You can download it directly through the [https://drive.google.com/file/d/1R-u3fkNxSOIG8bUmXbxTzPLSSj5iSWip/view?usp=sharing](link).

**Comment by jkonyourmark** [comment]
Thank you so much.
Have a wonderful day!

Best regards
Jisun Kim
________________________________
