### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by celalp** [TencentAI4S/tfold#10]
Hi, 

Thank you for this amazing work and the pretrained models. I was wondering if it's possible to share your training scripts as well. I am especially interested in the ESM-PPI model. 

Best, 
Alper

**Comment by wufandi** [comment]
Hi, 
Sorry, we are currently unable to provide the training scripts. However, we have provided extensive details in the paper, I think it is easy for readers to reproduce the results.

Best,
Fandi
