### ISSUE TITLE
icf.files.ppi

### ISSUE THREAD

**Issue by chiarinival** [TencentAI4S/tfold#8]
Hi!!! 

Congratulation for the amazing work!! I would like to ask about the following line:

# generate inter-chain feature (ppi)
python projects/tfold_ag/gen_icf_feat.py --pid_fpath=examples/prot_ids.abag.txt --fas_dpath=examples/fasta.files --pdb_dpath=examples/pdb.files.native --icf_dpath=examples/icf.files.ppi --icf_type=ppi

if it was possible to have a look a the "icf.files.ppi" which seems to be missing in the repository. Given that I assume it to be the output, does it calculate it directly from the input structures? Should the user input the ppi from some experimental evidence in the prediction script:

# antibody-antigen complex prediction with inter-chain feature
python projects/tfold_ag/predict.py --pid_fpath=examples/prot_ids.abag.txt --fas_dpath=examples/fasta.files --msa_fpath=examples/msa.files/8df5_R.a3m --pdb_dpath=examples/pdb.files.abag --icf_dpath=examples/icf.files.ppi --model_ver=ppi

 Could you provide some examples? All the rest (fasta.files/prot_ids.abag.txt etc) seems pretty clear.

Thanks a lot!!!

Valerio

**Comment by Cloud-Rambler** [comment]
Thank you for your interest in our work. I've put the files on ppi in the directory. You can check this using pytorch. Its contents are shown below. 1 represents contact and 0 is no contact.

<img width="643" alt="image" src="https://github.com/TencentAI4S/tfold/assets/69468968/4ca78563-cbd5-43d3-b282-df6e76c39b4b">

**Comment by Wolkenwandler** [comment]
> Hi!!!
> 
> Congratulation for the amazing work!! I would like to ask about the following line:
> 
> # generate inter-chain feature (ppi)
> python projects/tfold_ag/gen_icf_feat.py --pid_fpath=examples/prot_ids.abag.txt --fas_dpath=examples/fasta.files --pdb_dpath=examples/pdb.files.native --icf_dpath=examples/icf.files.ppi --icf_type=ppi
> 
> if it was possible to have a look a the "icf.files.ppi" which seems to be missing in the repository. Given that I assume it to be the output, does it calculate it directly from the input structures? Should the user input the ppi from some experimental evidence in the prediction script:
> 
> # antibody-antigen complex prediction with inter-chain feature
> python projects/tfold_ag/predict.py --pid_fpath=examples/prot_ids.abag.txt --fas_dpath=examples/fasta.files --msa_fpath=examples/msa.files/8df5_R.a3m --pdb_dpath=examples/pdb.files.abag --icf_dpath=examples/icf.files.ppi --model_ver=ppi
> 
> Could you provide some examples? All the rest (fasta.files/prot_ids.abag.txt etc) seems pretty clear.
> 
> Thanks a lot!!!
> 
> Valerio

Thank you for your interest in our work. I've put the files on ppi in the examples/icf.files.ppi directory. You can check this using pytorch. The contents of one of these files are shown below. 1 represents contact and 0 is no contact.

<img width="643" alt="image" src="https://github.com/TencentAI4S/tfold/assets/69468968/4ca78563-cbd5-43d3-b282-df6e76c39b4b">
